PUT http://localhost:5000/api/user/R4IMO
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlI0SU1PIiwiaWQiOiI2NTgwNGE5YWQzMWY2YzM3Y2UxMjMwNjEiLCJpYXQiOjE3MDI5NzgxMDgsImV4cCI6MTcwMzU4MjkwOH0.xf3P5nP33Hugu-gsfTzh-06CtmDvegDoNva2qRFRtUY
