POST http://localhost:5000/passwordReset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTcyZjIzODUzMDJjMmQ3OThmOGQzMTgiLCJpYXQiOjE3MDIzOTYwMzcsImV4cCI6MTcwMjM5OTYzN30.KROMP6hJ10swv2VRQuLmry_mSIvog5utYQBfiZiaWyI
Content-Type: application/json

{
    "password": "secret"
}