POST http://localhost:5000/signup
Content-Type: application/json

{
    "firstName": "cypressTest7",
    "lastName": "cypressTest7",
    "username": "cypressTest7",
    "password": "secret",
    "email": "cypressTest7@gmail.com"
}