name: ChatApp pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches: [master]
        types: [opened, synchronize]

jobs:
    ChatApp_deployment:
        runs-on: ubuntu-20.04
        timeout-minutes: 4
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: "20"
                
            - name: Run Build
              working-directory: ./server
              run: npm run build:ui
              
            - name: Run Lint
              working-directory: ./server
              run: npm run lint
            
            - name: Run Jest Chat
              working-directory: ./server
              run: npm run test chat.test.js
            
            - name: Run Jest Socket
              working-directory: ./server
              run: npm run test socket.test.js
            
            - name: Run Jest User
              working-directory: ./server
              run: npm run test user.test.js

            - name: Start server
              working-directory: ./server
              env:
                MONGODB_URI: ${{ secrets.MONGODB_URI }}
                PORT: ${{ secrets.PORT }}
                SECRET: ${{ secrets.SECRET }}
                ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
                ACCESSKEY: ${{ secrets.ACCESSKEY }}
                REGION: ${{ secrets.REGION }}
                USER_MAIL: ${{ secrets.USER_MAIL }}
                PASS_MAIL: ${{ secrets.PASS_MAIL }}
                EMAIL: ${{ secrets.EMAIL }}
                CLIENT_ORIGIN: ${{ secrets.CLIENT_ORIGIN }}
                CI: true
              run: npm start &
              
            - name: e2e tests
              uses: cypress-io/github-action@v5
              with:
                working-directory: ./client
                start: echo "Server already started"
                command: npm run e2e:userTest
                wait-on: http://localhost:5000 
                wait-on-timeout: 60

    tag-release:
        needs: [ChatApp_deployment]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Github Tag Bump
              if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
              uses: anothrNick/github-tag-action@1.67.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP : patch
